- app/src/main/java/com/github/ashutoshgngwr/noice/MainActivity.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/MediaPlayerService.kt
- app/src/test/java/com/github/ashutoshgngwr/noice/MainActivityTest.kt
- app/src/test/java/com/github/ashutoshgngwr/noice/MediaPlayerServiceTest.kt
- Audio playback getting resumed on clicking Play action button in notification while audio focus was lost (temporarily/permanently)
- Audio playback not getting stopped at losing audio focus (caused Service to not request focus when playback was started again)
- MainActivity refreshing/re-adding visible screen on clicking selected navigation item
- Added a lock to keep track of audio focus
- Stop rather than pause
- Missing `tag` in `FragmentTransaction#replace()` call
> Fixes a few minor bugs

- app/src/main/java/com/github/ashutoshgngwr/noice/SoundManager.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/fragment/PresetFragment.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/fragment/SoundLibraryFragment.kt
- app/src/test/java/com/github/ashutoshgngwr/noice/fragment/SoundLibraryFragmentTest.kt
- Uses a custom function to notify data set change to adapter. Adapter will reorder list before notifying changes.
-  Adds a new playback state update flag `OnPlaybackStateChangeListener.STATE_PLAYBACK_SETTINGS_UPDATED` to notify passive changes such as volume or time period change.
- Fixes: N/A
- Connects: N/A
> Adds list reordering based on item's playback state

- app/src/main/java/com/github/ashutoshgngwr/noice/MainActivity.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/fragment/AboutFragment.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/fragment/PresetFragment.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/fragment/SoundLibraryFragment.kt
It was being caused by forced night mode in `AboutFragment` due to which activity was recreated on opening about screen. Forcing night mode on `MainActivity` instead, solved the problem.
- Fixes #11 
- Connects N/A
> Fixes crash on opening about screen on Android 9+

- app/src/main/java/com/github/ashutoshgngwr/noice/fragment/PresetFragment.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/fragment/SoundLibraryFragment.kt
Temporary duct tape fix for app crash due to `MainActivity` recreation on opening `AboutFragment`.
- Fixes N/A
- Connects #11
> Adds null checks on RecyclerView in preset & sound library fragments

- app/src/main/java/com/github/ashutoshgngwr/noice/fragment/PresetFragment.kt
`PresetFragment` was crashing when a currently playing preset was deleted. This was happening because call to `onPlaybackStateChange()` was calling `notifyItemRangeChanged(0, dataSet.size)` which is not a valid call if the item was not removed from the ending position. 
- Fixes N/A
- Connects N/A
> fix(PresetFragment): app crash on deleting a playing preset

- .travis.yml
Explicitly add `dist: trusty` in Travis config. Android builds are currently supported only for trusty in Travis CI. See [this](https://docs.travis-ci.com/user/languages/android/)!
- Fixes N/A
- Connects N/A
> Fixes broken CI builds

- app/src/main/res/layout/layout_list_item__sound.xml
Earlier seeking the time period to minimum was setting time period to 0.
Time period is used as a modulo divisor when scheduling randomized playback.
This was causing division by zero errors.
- Set min value on time period seekbar
- Fixes #48
> Fixes crash/noplayback scenarios on playing randomized sounds

- .travis.yml
Most of the time build jobs fail randomly due to slowness of emulators. Hopefully this aids in fixing that.
- Changes Android versions in the build matrix
- Disables boot animation for emulator devices
- Fixes #0
- Connects #0
> Attempts to fix build matrix for CI

- app/src/main/java/com/github/ashutoshgngwr/noice/fragment/PresetFragment.kt
Publishing `StopPlaybackEvent` was causing `PlaybackManager` to send back State update when Play/Stop button was clicked. This resulted in a call to `notifyDataSetChanged()` on adapter which makes that `adapterPosition` negative. Assigning `adapterPosition` to a different variable isn't helping either.
- Fixes #0
- Connects #0
> Fixes playback control issues in PresetFragment

- app/build.gradle
- app/src/androidTest/java/com/github/ashutoshgngwr/noice/MainActivityTest.kt
- app/src/androidTest/java/com/github/ashutoshgngwr/noice/fragment/PresetFragmentTest.kt
- app/src/androidTest/java/com/github/ashutoshgngwr/noice/fragment/SavePresetDialogFragmentTest.kt
- app/src/androidTest/java/com/github/ashutoshgngwr/noice/fragment/SoundLibraryFragmentTest.kt
- app/src/androidTest/java/com/github/ashutoshgngwr/noice/sound/PlaybackTest.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/sound/Playback.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/sound/PlaybackManager.kt
Earlier, we were using Android's MediaPlayer for managing
playbacks. Android's MediaPlayer implementation doesn't
support true gapless playback for looping sounds. i.e.,
there is noticeable gap between loops.
Change playback backend to ExoPlayer.
- Fixes N/A
- Connects N/A
> Fixes unwanted gap in looping sounds

- app/src/main/java/com/github/ashutoshgngwr/noice/fragment/SleepTimerFragment.kt
The app would sometimes crash with following crash log. It is not clear why `onSaveInstanceState()` is being called when view is `null`. Regardless, it's nothing that a null check can not solve.
```
java.lang.IllegalStateException: Fragment did not return a View from onCreateView() or this was called before onCreateView().
at androidx.fragment.app.Fragment.requireView(Fragment.java:2)
at com.github.ashutoshgngwr.noice.fragment.SleepTimerFragment.d(SleepTimerFragment.java:2)
at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:5)
at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:5)
at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:5)
at …
```
> Adds view null check in onSaveInstanceState() of SleepTimerFragment

- app/src/androidTest/java/com/github/ashutoshgngwr/noice/sound/PlaybackTest.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/sound/Playback.kt
This was breaking compatibility after 0.3.0. Older versions used a Float data type for volumes while newer versions started using Int. This was an oversight and hence the fix.
Add a custom Serializer and Deserializer for volume field in playback
- Fixes #0
- Connects #0
> Fixes volume serialization/deserialization to/from JSON in Playback

- app/proguard-rules.pro
- app/src/main/java/com/github/ashutoshgngwr/noice/fragment/PresetFragment.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/sound/Playback.kt
- Added missing proguard rules for Gson library
- Explicitly specify field names to use for serialization/deserialization from older versions
- Fixes #110
- Connects N/A
> Fixes force close caused by the JSON deserialization after upgrading from 0.2.7 or older

- app/src/androidTest/java/com/github/ashutoshgngwr/noice/sound/PlaybackTest.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/sound/Playback.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/sound/PlaybackManager.kt
- Added fadeIn() and fadeOut() methods to the Playback class
- Minor changes to PlaybackManager to adapt new changes in Playback
- Fixes #122 
- Connects _N/A_
> Adds fade in-out effects to the playback

- app/src/main/java/com/github/ashutoshgngwr/noice/fragment/SavePresetDialogFragment.kt
- app/src/main/res/layout/dialog_save_preset.xml
- app/src/main/res/layout/layout_list_item__preset.xml
- app/src/main/res/values/styles.xml
- Fix SavePresetDialogFragment's appearance for light theme. See #126 
- Fix AlertDialog appearance throughout apps
- Fix delete button color in PresetFragment for light theme
- Fixes #126 
- Connects #0
> Fixes inconsistencies in app's appearance

- app/src/androidTest/java/com/github/ashutoshgngwr/noice/fragment/AboutFragmentTest.kt
- app/src/androidTest/java/com/github/ashutoshgngwr/noice/fragment/PresetFragmentTest.kt
- app/src/androidTest/java/com/github/ashutoshgngwr/noice/fragment/SavePresetDialogFragmentTest.kt
- app/src/androidTest/java/com/github/ashutoshgngwr/noice/fragment/SleepTimerFragmentTest.kt
- app/src/androidTest/java/com/github/ashutoshgngwr/noice/fragment/SoundLibraryFragmentTest.kt
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/ashutoshgngwr/noice/MainActivity.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/fragment/PresetFragment.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/fragment/SavePresetDialogFragment.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/fragment/SoundLibraryFragment.kt
- app/src/main/res/color/nav_view__item_text_color.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/dialog_save_preset.xml
- app/src/main/res/layout/fragment_sleep_timer.xml
- app/src/main/res/layout/layout_list_item__preset.xml
- app/src/main/res/layout/layout_list_item__sound.xml
- app/src/main/res/values-night/colors.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
- Use the new material components library
- Fix a minor issue with navigation view
- Fixes _N/A_
- Connects _N/A_
> Migrates Material design from AppCompat to MaterialComponents

- app/src/main/java/com/github/ashutoshgngwr/noice/fragment/SoundLibraryFragment.kt
Google Play Store reported a weird crash with following log. It is very infrequent and only happens on some devices.
```
java.lang.ArrayIndexOutOfBoundsException:
at com.github.ashutoshgngwr.noice.fragment.SoundLibraryFragment$SoundListAdapter$ViewHolder$1.onClick (SoundLibraryFragment.java:2)
at android.view.View.performClick (View.java:5280)
at android.view.View$PerformClick.run (View.java:21239)
at android.os.Handler.handleCallback (Handler.java:739)
at android.os.Handler.dispatchMessage (Handler.java:95)
at android.os.Looper.loop (Looper.java:234)
at android.app.ActivityThread.main (ActivityThread.java:5526)
at java.lang.reflect.Method.invoke (Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main …
```
> Fixes ArrayIndexOutOfBounds in SoundLibraryFragment's ViewHolder

- app/src/main/java/com/github/ashutoshgngwr/noice/MainActivity.kt
Issue #159 happens because service is stopped when activity is paused
for sometime after stopping the playback.
- Move `startService` call from `onCreate` to `onResume`
- Fixes #159 
- Connects _N/A_
> Fixes play button not responding to clicks

- app/src/androidTest/java/com/github/ashutoshgngwr/noice/fragment/SoundLibraryFragmentTest.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/fragment/PresetFragment.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/fragment/SoundLibraryFragment.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/sound/PlaybackManager.kt
The save preset button in the Sound library would not show when a saved preset was played and then volume or time period of a sound was readjusted. This is not the intended behavior. 
- Send update events for volume and time period updates from `PlaybackManager`
- Handle the update events in `SoundLibraryFragment` so they don't mess with on-going seek action by the user 
- Fixes _N/A_
- Connects #172
> Fixes save preset button not showing up sometimes

- app/src/main/java/com/github/ashutoshgngwr/noice/MainActivity.kt
- app/src/main/res/anim/enter_left.xml
- app/src/main/res/anim/enter_right.xml
- app/src/main/res/anim/exit_left.xml
- app/src/main/res/anim/exit_right.xml
Added a delay to close drawer in navigation item selected listener to avoid animation stutter. The delay prevents the fragment change and navigation drawer close animation
to start at the same time which was the cause of stutter.
> Fixes stutter during fragment change animation

- app/src/androidTest/java/com/github/ashutoshgngwr/noice/MainActivityTest.kt
- app/src/androidTest/java/com/github/ashutoshgngwr/noice/fragment/DialogFragmentTest.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/MainActivity.kt
- Add a workaround as suggested [here](https://issuetracker.google.com/issues/110237673#comment9).
- Fixes #179
> Fixes crash on starting service when resuming app from background

- app/src/main/java/com/github/ashutoshgngwr/noice/sound/Preset.kt
- app/src/test/java/com/github/ashutoshgngwr/noice/sound/PresetTest.kt
fix for offset corrections introduced in the following commits
1. https://github.com/ashutoshgngwr/noice/commit/b449ef643227b65685b71f7780a814c606e6abad
2. https://github.com/ashutoshgngwr/noice/commit/8ef502debd84aeadadaa665acd37c3cee592f521
3. https://github.com/ashutoshgngwr/noice/commit/11eb63ee22f3a03eca982cbd308f06ec164ab300#diff-db23b0e75244cdeb8ead7184bb06cb7cR15-R71
- Fixes _N/A_
- Connects #193
> Fixes incorrect time period offsets for saved presets

- .github/workflows/android.yaml
- app/src/androidTest/java/com/github/ashutoshgngwr/noice/EspressoX.kt
- app/src/androidTest/java/com/github/ashutoshgngwr/noice/MainActivityTest.kt
- app/src/androidTest/java/com/github/ashutoshgngwr/noice/fragment/DialogFragmentTest.kt
- app/src/androidTest/java/com/github/ashutoshgngwr/noice/fragment/PresetFragmentTest.kt
- app/src/androidTest/java/com/github/ashutoshgngwr/noice/fragment/SoundLibraryFragmentTest.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/MainActivity.kt
- app/src/main/res/drawable/ic_action_pause_to_play.xml
- app/src/main/res/drawable/ic_action_play_to_pause.xml
- app/src/main/res/values/ids.xml
> Adds play-pause toggle menu item to MainActivity

- app/src/main/java/com/github/ashutoshgngwr/noice/sound/player/Player.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/sound/player/PlayerManager.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/widget/CountdownTextView.kt
- app/src/test/java/com/github/ashutoshgngwr/noice/sound/player/PlayerManagerTest.kt
- Remove abandon audio focus call when playback is paused
- Add a method to stop playback with a delayed stop on indefinite paused
- Fix Handler#removeCallbacks calls (wasn't working with Kotlin function references)
- Fixes #219
> Fixes playback not resuming on gaining audio focus after a transient loss

- app/src/androidTest/java/com/github/ashutoshgngwr/noice/EspressoX.kt
- app/src/androidTest/java/com/github/ashutoshgngwr/noice/fragment/PresetFragmentTest.kt
- app/src/androidTest/java/com/github/ashutoshgngwr/noice/fragment/SoundLibraryFragmentTest.kt
- app/src/androidTest/java/com/github/ashutoshgngwr/noice/fragment/WakeUpTimerFragmentTest.kt
- app/src/androidTestPlaystore/java/com/github/ashutoshgngwr/noice/GenerateScreenshots.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/MainActivity.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/fragment/SoundLibraryFragment.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/fragment/WakeUpTimerFragment.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/sound/player/Player.kt
- app/src/main/res/layout/layout_list_item__sound.xml
- app/src/main/res/values/styles.xml
- app/src/playstore/java/com/github/ashutoshgngwr/noice/cast/CastOptionsProvider.kt
- Replace SeekBar with Sliders (displays value using ToolTips while sliding the thumb) in SoundLibraryFragment
- Add an informative message if the list is empty when selecting a preset in WakeUpTimerFragment
- Increase time period range (5 mins was too less)
> General Maintenance

- app/src/main/res/values-hi/strings.xml
- app/src/main/res/values/strings.xml
> Updates Hindi translations

- app/src/main/res/values-pt-rBR/strings.xml
This PR adds translations for missing items. I also took the liberty to change some terms that was already translated to terms that are commonly used by other apps. 
Those are:
- **Library**: "Biblioteca" alone is commonly used by many music players, so I felt that there's no need to provide more details for the user
- **Sleep timer**: "Temporizador" (pt-br) or just "Timer" (english word, but a known word to brazilians nowadays) is commonly used by music players to provide this same feature. I've aligned with the spanish translation to keep as Temporizador.
- Connects #200
> Update in Brazilian Portuguese translations

- app/src/main/java/com/github/ashutoshgngwr/noice/fragment/AboutFragment.kt
- app/src/main/res/values/dont_translate.xml
- fastlane/metadata/android/pt-BR/full_description.txt
Changed the fastlane metadata to match the current english metadata
- Connects #200 
- Connects https://github.com/ashutoshgngwr/noice/pull/381#issuecomment-711047176
> Update in Brazilian Portuguese translations for Fastlane Metadata

- app/src/main/java/com/github/ashutoshgngwr/noice/fragment/AboutFragment.kt
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values/dont_translate.xml
I am quit new here, but I have improved a little bit the German translation
> IMPROVE GERMAN TRANSLATION

- app/src/main/java/com/github/ashutoshgngwr/noice/AppIntroActivity.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/fragment/AppIntroFragment.kt
- app/src/main/res/layout/app_intro_fragment.xml
- app/src/main/res/layout/fragment_app_intro.xml
Added a Custom Fragment with a custom layout to solve text being cut off on small devices. This fragment has the exact same name that had the AppIntro library for its fragment, so you won't notice a change there.
- Resolves #505
> fix(app): Solve text being cut off on small devices!

- app/src/main/java/com/github/ashutoshgngwr/noice/engine/LocalSoundPlayer.kt
- app/src/main/java/com/github/ashutoshgngwr/noice/engine/media/DefaultMediaPlayer.kt
- app/src/test/java/com/github/ashutoshgngwr/noice/engine/LocalSoundPlayerTest.kt
This helps maintain behaviour parity among contiguous and non-contiguous sounds. In the current implementation, non-contiguous sounds stop immediately when the underlying media player is idle. It results in an incorrect preset state during `SoundPlayerManager`'s `PAUSING` and `STOPPING` transitions.
resolves #1155
> Fade-out sound players even when idle or buffering
