trynoice/android-app

app/src/main/java/com/github/ashutoshgngwr/noice/MainActivity.kt, app/src/main/java/com/github/ashutoshgngwr/noice/MediaPlayerService.kt, app/src/main/java/com/github/ashutoshgngwr/noice/fragment/PresetFragment.kt, app/src/test/java/com/github/ashutoshgngwr/noice/MainActivityTest.kt, app/src/test/java/com/github/ashutoshgngwr/noice/MediaPlayerServiceTest.kt
- Fix deprecancy in navigation menu updates
- Fix audio focus management (hopefully its correct now)
- Fix empty indicator (was always invisible on regaining focus, e.g. on pressing back button)
- Fixes: N/A
- Connects: #5
=> Fixes more minor bugs

.travis.yml, app/build.gradle, app/jacoco.gradle, app/src/main/java/com/github/ashutoshgngwr/noice/MainActivity.kt, app/src/test/java/com/github/ashutoshgngwr/noice/MainActivityTest.kt, app/src/test/java/com/github/ashutoshgngwr/noice/MediaPlayerServiceTest.kt, app/src/test/java/com/github/ashutoshgngwr/noice/SoundManagerTest.kt, app/src/test/java/com/github/ashutoshgngwr/noice/fragment/AboutFragmentTest.kt, app/src/test/java/com/github/ashutoshgngwr/noice/fragment/PresetFragmentTest.kt, app/src/test/java/com/github/ashutoshgngwr/noice/fragment/SavePresetDialogFragmentTest.kt, app/src/test/java/com/github/ashutoshgngwr/noice/fragment/SoundLibraryFragmentTest.kt
- Set compile and target SDK to Android Q
- Fixes N/A
- Connects N/A
=> Migrates to Android SDK 29

app/src/androidTest/java/com/github/ashutoshgngwr/noice/MainActivityTest.kt, app/src/androidTest/java/com/github/ashutoshgngwr/noice/fragment/SavePresetDialogFragmentTest.kt, app/src/androidTest/java/com/github/ashutoshgngwr/noice/sound/PlaybackManagerTest.kt, app/src/main/java/com/github/ashutoshgngwr/noice/MediaPlayerService.kt, app/src/main/java/com/github/ashutoshgngwr/noice/sound/PlaybackManager.kt
I was in a call and this happened.
- Fixes #0
- Connects #0
=> Fixes disappearing notification after losing audio focus temporarily

app/src/main/res/values-hi/strings.xml, app/src/main/res/values/strings.xml
Adds Hindi localization support
- Fixes #0
- Connects #108
=> Adds hindi translations

app/src/main/res/value-es-ar/strings.xml, app/src/main/res/value-es/strings.xml
Spanish translations
None
- Fixes #0
- Connects #108
=> Adds spanish translations

app/src/main/res/color/nav_view__item_text_color.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/values-night/colors.xml, app/src/main/res/values/colors.xml
- Fix navigation drawer width issue (#135)
- Fix selected item color in navigation drawer
- Fixes #135 
- Connects #0
=> Fixes minor issues with navigation view in main activity

.travis.yml
=> Optimizes CI build performance

app/src/androidTest/java/com/github/ashutoshgngwr/noice/fragment/PresetFragmentTest.kt, app/src/main/java/com/github/ashutoshgngwr/noice/fragment/PresetFragment.kt, app/src/main/res/menu/preset.xml, app/src/main/res/values/strings.xml
=> Adds rename option to PresetFragment

app/src/main/res/values-night/colors.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml
=> Adds 35% more darkness to the dark theme variant

app/src/androidTest/java/com/github/ashutoshgngwr/noice/MainActivityTest.kt, app/src/main/java/com/github/ashutoshgngwr/noice/MainActivity.kt
=> Updates MainActivity to update toolbar title when changing fragments

.gitignore, CONTRIBUTING.md, Gemfile, Gemfile.lock, app/build.gradle, app/src/androidTest/java/com/github/ashutoshgngwr/noice/EspressoX.kt, app/src/androidTestPlaystore/java/com/github/ashutoshgngwr/noice/GenerateScreenshots.kt, app/src/debug/AndroidManifest.xml, fastlane/Fastfile, fastlane/README.md, fastlane/Screengrabfile
=> Automates app screenshots using Fastlane Screengrab

app/src/androidTest/java/com/github/ashutoshgngwr/noice/fragment/SupportDevelopmentFragmentTest.kt, app/src/androidTest/java/com/github/ashutoshgngwr/noice/fragment/WakeUpTimerFragmentTest.kt, app/src/main/java/com/github/ashutoshgngwr/noice/fragment/SupportDevelopmentFragment.kt
=> Fixes share with friends action in Support Developement Fragment

README.md, app/src/androidTest/java/com/github/ashutoshgngwr/noice/MainActivityTest.kt, app/src/androidTestPlaystore/java/com/github/ashutoshgngwr/noice/GenerateScreenshots.kt, app/src/main/java/com/github/ashutoshgngwr/noice/MainActivity.kt, app/src/main/res/values/dont_translate.xml, app/src/playstore/res/values/dont_translate.xml
=> Enable cast icon in screenshots and adds compaign parameters to the Play Store URLs

app/src/androidTestPlaystore/java/com/github/ashutoshgngwr/noice/GenerateScreenshots.kt, app/src/main/java/com/github/ashutoshgngwr/noice/fragment/SoundLibraryFragment.kt, app/src/main/java/com/github/ashutoshgngwr/noice/sound/Sound.kt, app/src/main/java/com/github/ashutoshgngwr/noice/sound/player/Player.kt, app/src/main/java/com/github/ashutoshgngwr/noice/sound/player/strategy/LocalPlaybackStrategy.kt, app/src/main/res/layout/layout_list_item__preset.xml, app/src/main/res/layout/layout_list_item__sound.xml, app/src/main/res/layout/layout_list_item__sound_group_title.xml, app/src/main/res/values/strings.xml, app/src/playstore/java/com/github/ashutoshgngwr/noice/cast/player/strategy/CastPlaybackStrategy.kt, app/src/test/java/com/github/ashutoshgngwr/noice/sound/player/PlayerManagerTest.kt, app/src/test/java/com/github/ashutoshgngwr/noice/sound/player/PlayerTest.kt, app/src/testPlaystore/java/com/github/ashutoshgngwr/noice/cast/player/strategy/CastPlaybackStrategyTest.kt
- Add groups to sound library for categorization of sounds
- Resolves #173
=> Adds groups in sound library

app/src/main/res/values-cs/strings.xml
Please describe your changes to provide additional context.
- Fixes #0
- Connects #0
=> Updated czech translations

app/src/main/java/com/github/ashutoshgngwr/noice/sound/player/strategy/LocalPlaybackStrategy.kt, app/src/test/java/com/github/ashutoshgngwr/noice/sound/player/strategy/LocalPlaybackStrategyTest.kt
=> Enables fade transitions for volume updates during local playback

app/src/main/java/com/github/ashutoshgngwr/noice/fragment/AboutFragment.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values/dont_translate.xml
Added the german translations for the missing items from #200 .
- Not done yet. Could not build on my setup yet.
=> German translation for missing text items.

.github/workflows/cast-receiver.yaml, cast-receiver/yarn.lock
- Fixes broken parcel builds
- Fixes #0
- Connects #0
=> Fixes broken parcel builds

app/src/main/java/com/github/ashutoshgngwr/noice/fragment/PresetFragment.kt
=> Fixes duplicate presets when reopening the list again and again

app/src/androidTest/java/com/github/ashutoshgngwr/noice/fragment/WakeUpTimerFragmentTest.kt, app/src/androidTestPlaystore/java/com/github/ashutoshgngwr/noice/GenerateScreenshots.kt, app/src/main/java/com/github/ashutoshgngwr/noice/fragment/WakeUpTimerFragment.kt, app/src/main/res/layout/fragment_wake_up_timer.xml, app/src/main/res/values/strings.xml
=> Replaces DurationPicker with TimePicker for wake up timer

app/src/main/res/values-es-rES/strings.xml, fastlane/metadata/android/es-ES/full_description.txt
Updated Spanish translation files, F-Droid/Play Store metadata according to the instructions. The author of the change does not need to be attributed.
=> Update spanish translation

app/src/androidTest/java/com/github/ashutoshgngwr/noice/AppIntroActivityTest.kt, app/src/main/java/com/github/ashutoshgngwr/noice/AppIntroActivity.kt
- A blind attempt
- Fixes #320
=> Fixes flaky tests in AppIntroActivity

app/src/main/res/values-cs/strings.xml
I've translated some newly added english strings to czech.
- [] Tested on a physical device
- [] Added or modified unit test cases
Connects #200
=> Updated czech translations with translated new strings

app/build.gradle
- closes #294
- closes #295
- closes #297
- closes #298
- closes #299
=> chore(app): bump android testing stack

app/src/main/java/com/github/ashutoshgngwr/noice/fragment/AboutFragment.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values/dont_translate.xml
Small corrections for German translations
- Fixes #0
- Connects #0
=> German translations

app/build.gradle
Some recent change in ExoPlayer is causing gaps in looping sounds. Reverting to provide a temporary fix for issue #344.
- Connects https://github.com/google/ExoPlayer/issues/7994
- Connects #344 
- Connects #330
=> Reverts PR #330 to downgrade ExoPlayer to 2.11.8

app/src/androidTest/java/com/github/ashutoshgngwr/noice/fragment/SoundLibraryFragmentTest.kt, app/src/main/java/com/github/ashutoshgngwr/noice/fragment/DialogFragment.kt, app/src/main/java/com/github/ashutoshgngwr/noice/fragment/SoundLibraryFragment.kt, app/src/main/java/com/github/ashutoshgngwr/noice/sound/Preset.kt, app/src/main/java/com/github/ashutoshgngwr/noice/sound/Sound.kt, app/src/main/res/drawable/ic_action_shuffle.xml, app/src/main/res/layout/fragment_dialog__random_preset.xml, app/src/main/res/layout/fragment_sound_list.xml, app/src/main/res/layout/layout_list_item__sound.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml, app/src/test/java/com/github/ashutoshgngwr/noice/sound/SoundTest.kt
=> Adds generate random preset action button

app/src/main/java/com/github/ashutoshgngwr/noice/fragment/AboutFragment.kt, app/src/main/res/values-tr/strings.xml, app/src/main/res/values/dont_translate.xml, fastlane/metadata/android/tr/full_description.txt, fastlane/metadata/android/tr/short_description.txt, fastlane/metadata/android/tr/title.txt
Followed [instructions](https://github.com/ashutoshgngwr/noice/blob/master/docs/CONTRIBUTING.md#translations) for Turkish translate
=> Add Turkish translatiın

app/src/main/res/values-tr/strings.xml, fastlane/metadata/android/tr-TR/full_description.txt, fastlane/metadata/android/tr-TR/title.txt
Previous PR had conflicts and i couldn't fix it. I deleted that repo and created new one. Now it's clean and correct.
- Made translation more accurate
- Made translation more clear and simple
- Made translation more official
=> Improvments for Turkish translation

app/src/main/res/values-cs/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es-rAR/strings.xml, app/src/main/res/values-es-rES/strings.xml, app/src/main/res/values-fr-rFR/strings.xml, app/src/main/res/values-hi/strings.xml, app/src/main/res/values-in/strings.xml, app/src/main/res/values-it-rIT/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sq-rAL/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-uk-rUA/strings.xml, app/src/main/res/values/strings.xml, fastlane/metadata/android/tr-TR/full_description.txt
- Fix #442 
- Fix small misspellings on Turkish tranlation
=> Tidying up the 'strings.xml' files for #442

app/build.gradle, app/src/main/java/com/github/ashutoshgngwr/noice/fragment/AboutFragment.kt, app/src/main/res/navigation/main.xml, build.gradle, gradle.properties, settings.gradle
=> Replace gms oss-licenses-plugin with aboutlibraries plugin

README.md
I also suggest to update the project description on GitHub and add some topics to improve discoverability.
PS: BTW, Noice v2 works amazingly well, v1 used to stop streaming audio randomly, now this does not happen anymore, and the sound quality is much better, and v1 was already great. Also the WombSimulator works perfectly well, better than the v1 version ;-)
=> docs: Add a short description of what Noice is
